### ISSUE TITLE
VSCode extension

### ISSUE THREAD

**Issue by davidivkovic** [kiegroup/drools-lsp#16]
Hello, is there a VSCode extension we can simply download?

Thank you!

**Comment by tkobayas** [comment]
Thank you for the interest. VSCode extension release is not yet ready. I filed https://issues.redhat.com/browse/DROOLS-7396 for the task. Thank you for your patience!

**Comment by tkobayas** [comment]
Hello, now you can download `vscode-extension-drl-editor-1.0.0-alpha.vsix` at https://github.com/kiegroup/drools-lsp/releases
You can install it with
```
code --install-extension vscode-extension-drl-editor-1.0.0-alpha.vsix
```
It's still alpha. It implements highlighting and code-completion. Enjoy!
