### ISSUE TITLE
How can I contribute to this project?

### ISSUE THREAD

**Issue by guglielmobartelloni** [kiegroup/drools-lsp#49]
I think that the community really needs an lsp for drools. I will be happy to help in any way possible

**Comment by mariofusco** [comment]
We put this project aside for a bit waiting for having a fully working antlr4 based parser in drools, which is necessary for this LSP implementation. We have that parser ready in a branch now and we will merge it into Drools main immediately after Drools 10.0 will be out. At that point we will be able to also restart the development also of this project.
